name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.2.6
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  googleapis: ^1.0.0
  googleapis_auth: ^1.0.0
  http: ^0.13.0
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
